services:
  - type: web
    name: quantengine
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python migrate.py
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        generateValue: true